- .github/workflows/build.yaml
- Cargo.toml
- src/utils.rs
With this util, we add a way to generate and verify a keypair. The keypair generation is useful for first installation, especially when https://github.com/rustdesk/rustdesk-server/pull/61 gets approved.
The command will be something like:
```bash
docker run --rm --entrypoint /usr/bin/rustdesk-utils rustdesk/rustdesk-server:latest genkeypair
```
The expected output is something like this:
```text
Public Key:  e61C1tOULMqVbAf0kTlUbyBFNZ1eObXIOQ1O0BSSB/o=
Secret Key:  ZuDfy4g9/HO1U6003hTQSaFQNBT7XPpz4B4F2TOw9Uh7rULW05QsypVsB/SROVRvIEU1nV45tcg5DU7QFJIH+g==
```
The other available command is `validatekeypair` which is used to check if the keypair is valid:
```bash
rustdesk-utils validatekeypair 'e61C1tOULMqVbAf0kTlUbyBFNZ1eObXIOQ1O0BSSB/o=' …
```
> small util for key management

- docker-compose.yml
The services hbbs and hbbr must use the same volume. Otherwise, different keys are used when encryption is enabled.
> Use same volumes for hbbs and hbbr

- .github/workflows/build.yaml
when a manual build is triggered, the "version" is not 1.3.6 but the branch name (master, main, fix-docker-manifest, ...) so the github action tries to make a manifest 2 times with the same tag and this lead the action to fail.
this just skip one of the two manifest if the action is manually triggered.
> fix github action on manual build

- README.md
- docker/rootfs/etc/s6-overlay/s6-rc.d/key-secret/up.real
simple as that.
Either you start the container with a valid keypair or with no keypair (and it gets generated as usual)
> keypair verification before container startup

- README.md
- debian/rules
now deb packages are debian compatible.
tested with debian 11 (stable) and debian 10 (oldstable)
tested also with supported ubuntu (server)
> debian support

- .github/workflows/build.yaml
- README.md
Every time the build action is run (on every tag), a zip file is created, for each architecture.
As an example, the `rustdesk-server-linux-amd64.zip` file contains this binaries:
- amd64/hbbr
- amd64/hbbs
- amd64/rustdesk-utils
```bash
~$ unzip -t rustdesk-server-linux-amd64.zip
Archive:  rustdesk-server-linux-amd64.zip
testing: amd64/hbbr               OK
testing: amd64/hbbs               OK
testing: amd64/rustdesk-utils     OK
No errors detected in compressed data of rustdesk-server-linux-amd64.zip.
```
> Zipped release binaries

- Cargo.toml
- src/utils.rs
I added a small util to be run on a client machine to test for connectivity problems.
Example:
```bash
$ rustdesk-server doctor myrelay.rustdesk.com
Checking server:  myrelay.rustdesk.com
Found 1 IP addresses: 
- 123.456.123.456
Checking IP address: 123.456.123.456
Is IPV4: true
Is IPV6: false
Reverse DNS lookup: 'vps444.provider.com' DOESN'T MATCH server address 'myrelay.rustdesk.com'
TCP Port 21114 (API): OK in 25 ms
TCP Port 21115 (hbbs extra port for nat test): OK in 21 ms
TCP Port 21116 (hbbs): OK in 21 ms
TCP Port 21117 (hbbr tcp): OK in 21 ms
TCP Port 21118 (hbbs websocket): OK in 24 ms
TCP Port 21119 (hbbr websocket): OK in 21 ms
```
I would like to add some more checks, like:
- ICMP ping (maybe not needed)
- key support (key required or not, check if a provided key is valid)
- …
> rustdesk-server doctor

- docker/rootfs/etc/s6-overlay/s6-rc.d/hbbr/run
The [documentation](https://rustdesk.com/docs/en/self-host/install/#key) suggests that `-k _` should be supplied to both `hbbs` and `hbbr` when only encrypted connections are permitted, but the [`rustdesk-server-s6`](https://hub.docker.com/r/rustdesk/rustdesk-server-s6) container doesn't appear to be doing this.
> If you want to prohibit users without the key from establishing non-encrypted connections, please add the -k _ parameter when running hbbs and hbbr, for example:
> `./hbbs -r <relay-server-ip[:port]> -k _`
> `./hbbr -k _`
Am I correct in understanding that anyone could currently be using the relay server (`hbbr`), even if `ENCRYPTED_ONLY=1`? ... and that the relay server will carry the majority of the bandwidth commitments, so it would be "_inviting_" to locate someone else's? …
> add '-k _' to hbbr if ENCRYPTED_ONLY is set

- Cargo.toml
Crate.io package local-ip-address from v0.5+ is Freebsd compatible, eg. it compiles and works. Simply changing the version to v0.5.1 in the Cargo.toml of rustdesk-server was possible to make a successful release build on FreeBSD 13 with prepackaged Rust 1.67.1. Working rc scripts available too.
Beyond the actual change, thinking about including FreeBSD release builds in the official releases.
> Update Cargo.toml for FreeBSD build

- rcd/rustdesk-hbbr
- rcd/rustdesk-hbbs
Working rcd scripts, tested on FreeBSD 13 with other different service users (added manually in /etc/rc.conf).
The default user/group set to rustdesk. Can be used in two way:
A. With specifying hubs & hubby user and group at the end of /etc/rc.conf for example:
rustdesk_hbbs_user=existing_service_user
rustdesk_hbbs_group=existing_service_group
...
B. The default user need to be created with a command like:
pw adduser rustdesk -d /nonexistent -s /usr/sbin/nologin -c "Rustdesk Server user"
If can be put In the rcd scripts too, but it should be placed & handled more in and overall install script, or native package scripts 
Works both ways.
> FreeBSD rcd scripts for hbbs & hbbr

- .github/workflows/build.yaml
After some discussions in Issue #209 , got the direction to turn directly to the workflow -> build process.
Reading about the Actions, it seemed logical to put the new os/arc build in the matrix to the end, but in the GitHub release part before the windows build.
> Update build.yaml - adding FreeBSD build

- rcd/rustdesk-hbbr
- rcd/rustdesk-hbbs
Logging over syslog added via a semi-duplicate line commented out by default. Instructions in the line above.
> Adding log capability over syslog

- .github/workflows/build.yaml
Based on https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/, the 18.04 will be deprecated soon. Also moving toolchain to 1.68 to hopefully fix auto-build's FreeBSD release core dump issue.
> Move from Ubuntu 18.04 VM (Github Actions)

- Cargo.toml
- rcd/rustdesk-hbbr
- rcd/rustdesk-hbbs
3 commits
- Core dump fix with (the possible) root cause Flexi_logger options for async writemode https://github.com/rustdesk/rustdesk-server/pull/232#issuecomment-1491347232
- removing need to edit rc.d scripts before use, necessary variables can be set over /etc/rc.conf, default IP set to 127.0.0.1 based on Freshport changes
> Core dump fix and rc.d scripts optimisation for FreeBSD

- src/rendezvous_server.rs
We had multiple peers all connecting via VPN to a network that was hosting the rendezvous and relay servers. However none of the peers were able to establish a direct connection, even though they had no trouble using direct IP access. Having set `--mask` to `10.0.0.0/8` made no difference.
After some debugging, we found that `is_lan()` was returning false for any of our peers' IP addresses, even though these peers were using IPs that were well within the network we specified using `--mask`. Turns out, our IPv4 addresses were noted as [IPv4-mapped IPv6 addresses](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html#ipv4-mapped-ipv6-addresses) (i.e. `::ffff:10.50.55.22`). `is_lan()` has been improved to take these type of addresses into account.
Further more, the calculation of the …
> Fix no direct connection when both peers on LAN

- rcd/rustdesk-hbbr
- rcd/rustdesk-hbbs
Here are some updates to the rc scripts:
- Some comments where wrong, with lines referencing nfs-exporter
- Updated the defaults for _args
- Quotes are unneeded around the _chdir variables, as long as the path does not include spaces
- Changed the chdir directory to /var/db, according to FreeBSD hier(7) man page.
Noticed while looking for a fix to #288
> FreeBSD rc scripts fixes

- docker-classic/Dockerfile
I just realized that there's no need to have a full-blown ubuntu image if you're using only the hbbr/hbbs binaries.
This reduces the image size from ~100Mb to around 25Mb.
> minimal docker classic images

- src/rendezvous_server.rs
throw an error and quit if the length of the secret key is incorrect.
> private key size check

- rcd/rustdesk-hbbs
Since the "rustdesk_hbbs_ip" is not where the server should listen on, but actually the relay server to use, I added a description that will clarify this
> Add description of relay server variable for clarity

- docker/Dockerfile
* Bump s6-overlay to [v3.2.0.0](https://github.com/just-containers/s6-overlay/releases/tag/v3.2.0.0).
* Fix `LegacyKeyValueFormat` warnings
Error will shown while building:
```
2 warnings found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 15)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 16)
```
Solution: Add `=` between env name and value
```dockerfile
ENV RELAY=relay.example.com
ENV ENCRYPTED_ONLY=0
```
> Bump s6-overlay to v3.2.0.0 and fix env warnings

- src/main.rs
Based on the code at https://github.com/rustdesk/rustdesk-server/blob/master/src/common.rs#L42
> docs: the servers are by comma instead of colon

- .github/workflows/ghcr.yml
https://github.com/rustdesk/rustdesk-server/issues/465
* No any `secrets` needed to run this action, you could try after you merged, or [you could check my action.](https://github.com/xlionjuan/rustdesk-server/actions/workflows/ghcr.yml)
* All actions in it are latest
* All runners are use `ubuntu-24.04`, no any problem found
I've published to [ghcr.io/xlionjuan/rustdesk-server](https://github.com/xlionjuan?tab=packages&repo_name=rustdesk-server) in order to test.
I've test:
* `ghcr.io/xlionjuan/rustdesk-server`
* `latest` tag
* `latest-amd64` tag
* `latest-i386` tag
* `ghcr.io/xlionjuan/rustdesk-server-s6`
* `latest` tag
* `latest-amd64` tag
* `latest-i386` tag
I only have x86 machine, but other architectures should works in theory.
> feat: Publish container images to GitHub ghcr.io

- README.md
#478 
* L35: releases to Releases to match GitHub UI
* L37: Add comma
* L43: Add ghcr
* L47:
* Classic isn't Ubuntu based anymore
* Add ghcr
* Del arch specific tag, *we should guide user use merged tags*
* Restructure expression
* L122:
* `hbbs` first than `hbbr` everywhere
* Add ghcr
* Del arch specific tag, *we should guide user use merged tags*
* Restructure expression
* L118:
* GitHub style NOTE
* Add `
* Suggest user use ghcr if they can't access Docker Hub
* L251:  Capital the term: Docker Swarm
* L324: releases to Releases to match GitHub UI
* L329,333: Add Ubuntu 24 and Debian 12
* L335: Add `
> README: Restructure Container expression; add ghcr; multiple tidy up

- src/utils.rs
in command help is used wrong name
> In cargo it is named "rustdesk-utils"
